/*
 * This file is part of Tectuinno IDE.
 *
 * Tectuinno IDE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, you may use this file as part of a free software
 * library without restriction. Specifically, if other files instantiate
 * templates or use macros or inline functions from this file, or you compile
 * this file and link it with other files to produce an executable, this
 * file does not by itself cause the resulting executable to be covered by
 * the GNU General Public License. This exception does not however
 * invalidate any other reasons why the executable file might be covered by
 * the GNU General Public License.
 *
 * Copyright 2025 Tectuinno Team (https://github.com/tectuinno)
 */

package org.tectuinno.compiler.assembler.utils;

import java.util.List;

import org.tectuinno.compiler.assembler.EncoderIrLine;
import org.tectuinno.compiler.assembler.IrLine;

/**
 * Utility class that builds a human-readable assembly listing from
 * second-pass encoded lines.
 *
 * <p>The listing includes structural and encoding information for each line:</p>
 * <ul>
 *     <li>Address</li>
 *     <li>Optional label</li>
 *     <li>IR kind</li>
 *     <li>Original source line</li>
 *     <li>Emitted byte count</li>
 *     <li>Optional 32-bit instruction word</li>
 *     <li>Raw emitted bytes</li>
 *     <li>Display hexadecimal representation</li>
 * </ul>
 *
 * @author Pablo
 * @version 2.0
 * @since 2025-08-14
 */
public final class AsmListingFormatter {

	private AsmListingFormatter() {}

	/**
	 * Builds a formatted listing table for encoded lines.
	 *
	 * @param list encoded lines generated by the second assembler pass
	 * @return formatted listing as a printable string
	 */
	public static String buildListing(List<EncoderIrLine> list) {
		StringBuilder sb = new StringBuilder();

		sb.append(String.format(
				"%-10s %-12s %-12s %-34s %-6s %-12s %-28s %s%n",
				"Dirección",
				"Etiqueta",
				"Tipo",
				"Instrucción",
				"Size",
				"WordOpt",
				"Bytes",
				"Hex"
		));

		sb.append("----------------------------------------------------------------------------------------------------------------------------------------\n");

		for (EncoderIrLine ln : list) {
			String addr = String.format("%08X", ln.pc());
			String label = ln.labelOpt() == null ? "" : ln.labelOpt();
			String kind = ln.kind() == null ? "" : ln.kind().name();
			String instr = safeText(ln.originalText(), 34);
			String size = String.valueOf(ln.size());
			String wordOpt = formatWordOpt(ln.wordOpt());
			String bytes = formatBytes(ln.bytes(), 28);
			String hex = ln.hex() == null ? "" : ln.hex();

			sb.append(String.format(
					"%-10s %-12s %-12s %-34s %-6s %-12s %-28s %s%n",
					addr,
					label,
					kind,
					instr,
					size,
					wordOpt,
					bytes,
					hex
			));
		}

		return sb.toString();
    }
	
	/**
	 * Formats an optional instruction word.
	 *
	 * @param wordOpt optional 32-bit encoded word
	 * @return formatted hexadecimal word or empty string if absent
	 */
	private static String formatWordOpt(Integer wordOpt) {
		if (wordOpt == null) {
			return "";
		}
		return String.format("0x%08X", wordOpt);
	}

	/**
	 * Formats emitted bytes as uppercase hexadecimal pairs separated by spaces.
	 *
	 * @param bytes emitted bytes
	 * @param maxLen maximum output width before truncation
	 * @return printable byte representation
	 */
	private static String formatBytes(byte[] bytes, int maxLen) {
		if (bytes == null || bytes.length == 0) {
			return "";
		}

		StringBuilder sb = new StringBuilder(bytes.length * 3);

		for (int i = 0; i < bytes.length; i++) {
			if (i > 0) {
				sb.append(' ');
			}
			sb.append(String.format("%02X", bytes[i] & 0xFF));
		}

		return safeText(sb.toString(), maxLen);
	}

	/**
	 * Truncates text to a fixed width for console-friendly alignment.
	 *
	 * @param text source text
	 * @param maxLen maximum length
	 * @return original or truncated text
	 */
	private static String safeText(String text, int maxLen) {
		if (text == null) {
			return "";
		}

		if (text.length() <= maxLen) {
			return text;
		}

		if (maxLen <= 3) {
			return text.substring(0, maxLen);
		}

		return text.substring(0, maxLen - 3) + "...";
	}
	
}
