/*
 * This file is part of Tectuinno IDE.
 *
 * Tectuinno IDE is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 *
 * As a special exception, you may use this file as part of a free software
 * library without restriction. Specifically, if other files instantiate
 * templates or use macros or inline functions from this file, or you compile
 * this file and link it with other files to produce an executable, this
 * file does not by itself cause the resulting executable to be covered by
 * the GNU General Public License. This exception does not however
 * invalidate any other reasons why the executable file might be covered by
 * the GNU General Public License.
 *
 * Copyright 2025 Tectuinno Team (https://github.com/tectuinno)
 */

package org.tectuinno.view.component;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import java.awt.BorderLayout;
import javax.swing.JTextArea;
import javax.swing.text.DefaultCaret;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.Locale;

public class TokenTerminalPanel extends JPanel {

	private static final long serialVersionUID = 1L;
	private final JScrollPane scrollPane = new JScrollPane();
	private final JTextArea txaTokenListResult = new JTextArea();

	/**
	 * Create the panel.
	 */
	public TokenTerminalPanel() {
		setLayout(new BorderLayout(0, 0));
		{
			add(scrollPane);
		}
		{
			String initialText = this.setInitialText();
			this.txaTokenListResult.setText(initialText);
			txaTokenListResult.setLocale(Locale.forLanguageTag("es-MX"));
			Color accentPurple = new Color(187, 134, 252);
			txaTokenListResult.setForeground(new Color(0xff, 0xe6, 0x6d)); // terminal.ansiYellow #ffe66d
			txaTokenListResult.setFont(new Font("Consolas", Font.PLAIN, 13));
			txaTokenListResult.setEditable(false);
			txaTokenListResult.setCursor(Cursor.getPredefinedCursor(Cursor.TEXT_CURSOR));
			txaTokenListResult.setCaretColor(accentPurple);
			txaTokenListResult.setSelectionColor(accentPurple.darker());
			txaTokenListResult.setBackground(new Color(0x0c, 0x0e, 0x14)); // #0c0e14
			((DefaultCaret) txaTokenListResult.getCaret()).setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
			scrollPane.setViewportView(txaTokenListResult);
		}

	}
	
	/**
     * Writes the provided text, preceded by the
     * default header text generated by {@link #setInitialText()}.
     *
     * @param text the disassembly output to display
     */
	public void writteIn(String text) {
		//this.txaTokenListResult.setText("");
		//this.txaTokenListResult.setText(this.setInitialText());
		//this.txaTokenListResult.append("\n");
		this.txaTokenListResult.append(text);
		this.txaTokenListResult.setCaretPosition(this.txaTokenListResult.getDocument().getLength());
	}

	public void reset() {
		this.txaTokenListResult.setText(this.setInitialText());
		this.txaTokenListResult.setCaretPosition(this.txaTokenListResult.getDocument().getLength());
	}
	
	private final String setInitialText() {
		
		return new StringBuilder()
				.append("\n")
				.append("**********************************************************************************\n\r")
				.append("\t Lista de tokens \n")
				.append("**********************************************************************************\n\r")
				.toString();
		
	}

}
